### PR TITLE
fix(lsp): enforce lvim completion for lua-server

### LINKED ISSUE #3002: lua-dev config broken
### Problem description

The recent update of https://github.com/folke/lua-dev.nvim deprecate the `lspconfig` field, which breaks our customized lsp config.

### LunarVim version

rolling-2519e074

### Neovim version (>= 0.7)

NVIM v0.7.2

### Operating system/version

archlinux

### Affected language servers

sumneko_lua

### Steps to reproduce

_No response_

### Actual behavior

For example, `vim`, `packer_plugins` as global for diagnostics don't take effect.

### Expected behavior

_No response_

### support info

```console
 Use [q] or [Esc] to quit the window
 
 Language client log: /home/jmei/.cache/nvim/lsp.log
 Detected filetype:   lua
 
 2 client(s) attached to this buffer: 
 
 Client: sumneko_lua (id: 1, pid: 8170, bufnr: [1])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /home/jmei/lib/LunarVim
 	cmd:             lua-language-server
 
 Client: null-ls (id: 2, pid: 5001, bufnr: [1])
 	filetypes:       cpp, lua
 	autostart:       false
 	root directory:  /home/jmei/lib/LunarVim
 	cmd:             nvim
 
 Configured servers list: sumneko_lua
```

### logs

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by kylo252**
# Description

`lua-dev` has changed the way it accepts settings, this will now hopefully accommodate those changes!

- fix `lvim.` auto-completion in `config.lua`
- add a select list of plugins by default that should always have auto-completion
  ```lua
  plugins = { "plenary.nvim", "telescope.nvim", "nvim-treesitter", "packer.nvim", "LuaSnip" }
  ```

fixes #3002

## How Has This Been Tested?

- open `config.lua` start typing `lvim.builtin.telescope.`
- open `config.lua` start typing `require'packer.`

### CODE REVIEW

File: lua/lvim/lsp/providers/sumneko_lua.lua [hunk 1]
```diff
@@ -4,16 +4,41 @@ local dev_opts = {
...
+    -- this is otherwise getting overwritten by lua_dev.lsp.on_new_config()
+    new_config.settings.Lua = new_config.settings.Lua or { workspace = { library = {} } }
+    table.insert(new_config.settings.Lua.workspace.library, get_lvim_base_dir())
+  end)
+end
+
+lspconfig.util.default_config = vim.tbl_extend("force", lspconfig.util.default_config, {
+  on_new_config = make_on_new_config(lspconfig.util.default_config.on_new_config),
+})
+
```
Comment (lvimuser) [inline lua/lvim/lsp/providers/sumneko_lua.lua:41]: I suppose passing `on_new_config` in `opts` doesn't work? 
Alternatively, `lua_dev.setup()` returns the settings, so we could try `return vim.tbl_deep_extend("force", luadev, opts)`

Comment (kylo252) [reply lua/lvim/lsp/providers/sumneko_lua.lua:41]: > I suppose passing `on_new_config` in `opts` doesn't work?

that one is getting overwritten unfortunately, I nearly want to write our own `lua_dev.setup()` and skip this entire dance..

**Comment by abzcoding** [comment]
@kylo252 I just removed my custom config and used this instead, and it worked just fine,
not sure about customization though

**Comment by abzcoding** [comment]
Also, I'm not sure if we need all of those plugins activated or not
```
 { "plenary.nvim", "telescope.nvim", "nvim-treesitter", "packer.nvim", "LuaSnip" }
 ```
 it seems a bit much
Screenshot 2022-09-18 at 7 24 25 PM

**Comment by lvimuser** [comment]
Agree with abz. I don't think plenary should be a default either...
Maybe leave it empty for now?

File: lua/lvim/lsp/providers/sumneko_lua.lua (hunk 1 above)
Comment (lvimuser) [reply lua/lvim/lsp/providers/sumneko_lua.lua:42]: > Alternatively, lua_dev.setup() returns the settings, so we could try return vim.tbl_deep_extend("force", luadev, opts)

It seems that `nlspsettings` overrides the configuration in that case (not sure if it's a bug / intended or something else going on). So that might not work either...

**Comment by kylo252** [comment]
> it seems a bit much

I did change the `maxPreload=1000`, and it was pretty fast, but I have only tested on a single machine

> Agree with abz. I don't think plenary should be a default either...
> Maybe leave it empty for now?

the way I think about it is that you'd want these kind of completion for a nice dev environment:
- plenary: async, busted, curl, etc
- telescope: custom finders
- luasnip: snippets API
- treesitter: extended API that's not yet available in core
- packer: alternative async impl (probably not that useful)

I'll try to see if I can get the lua server to ignore `test{s}` directories, and how much would that save us.

**Review by abzcoding — APPROVED** [review]
thanks @kylo252, it is much faster now

LGTM 🚀

**Comment by lvimuser** [comment]
> I did change the `maxPreload=1000`, and it was pretty fast, but I have only tested on a single machine
> 
I missed that, looks pretty good!
