### PR TITLE
Fix the lua goto definition bug and add better common capabilities

### LINKED ISSUE #1603: [Bug]: can't get `gd` to work properly in lua projects
### Problem description

I used `LunarVim` for a mouth and I am really suprised by it's amazing customizability and user-friendly. I have solved many little stuff in my daily usage of lunarvim by searching for the project's issues or reading the source code most of time. But I stilll confused by this problem and can't solve it from the first time when I used lunarvim.

This problem is that `gd` can't take me to tables and functions that need `require`, though they are defined in current lua project. It only take me to tables and functions defined in current buffer as well as builtin types and functions.

Take lunarvim source as an example. The situation that `gd` doesn't work:

```lua
-- https://github.com/LunarVim/LunarVim/blob/rolling/init.lua#L6
require("bootstrap"):init() -- Here I can't go to definition of module `bootstrap` or function `init`

-- https://github.com/LunarVim/LunarVim/blob/rolling/lua/bootstrap.lua#L49
self.runtime_dir = get_runtime_dir() -- Here I can go to function `get_runtime_dir`, it is defined is this file
```

This problem only happened in lua project with lua-lsp `sumneko_lua` installed. And I had test some other language (python, c++, go, rust) with lsp installed and `gd` worked properly.

I reinstalled `sumneko_lua` many times and try in another computer but the problem is still there.

### Check the following

- [X] I am in a git managed directory
- [X] I restarted Neovim after running :LspInstall
- [X] I have a valid language configuration (~/.config/lvim/ftplugin/)
- [X] I checked the options (~/.config/lvim/config.lua)
- [x] The programs specified by the config are installed

### LunarVim version

0.5.1

### Neovim version (>= 0.5)

0.5.0

### Relevant log output

```shell
Language client log: /home/xavier/.cache/nvim/lsp.log
 Detected filetype:   lua
 
 2 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, pid: 5001, bufnr: [3, 3, 21, 24, 8])
 	filetypes:       lua
 	autostart:       false
 	root directory:  /home/xavier/.config/lvim
 	cmd:             nvim
 
 Client: sumneko_lua (id: 2, pid: 14911, bufnr: [3, 21, 21, 24, 24, 8, 8])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /home/xavier/.config/lvim
 	cmd:             /home/xavier/.local/share/nvim/lspinstall/lua/sumneko-lua-language-server -E /home/xavier/.local/share/nvim/lspinstall/lua/main.lua
 
 Configured servers list: lua, null-ls, python, go, sumneko_lua, rust, cpp
```

### Screenshots

_No response_

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

The goto definition didn't properly work in lunarvim

Fixes #1603

## How Has This Been Tested?

for example go to init.lua over at `init` part, in this line
```lua
require("bootstrap"):init()
```
and run `gd`, that should move you to the definition in `bootrap.lua`

### CODE REVIEW

File: lua/lsp/init.lua [hunk 1]
```diff
@@ -47,6 +47,13 @@ end
 
 function M.common_capabilities()
   local capabilities = vim.lsp.protocol.make_client_capabilities()
+  capabilities.textDocument.completion.completionItem.documentationFormat = { "markdown", "plaintext" }
+  capabilities.textDocument.completion.completionItem.preselectSupport = true
+  capabilities.textDocument.completion.completionItem.insertReplaceSupport = true
+  capabilities.textDocument.completion.completionItem.labelDetailsSupport = true
+  capabilities.textDocument.completion.completionItem.deprecatedSupport = true
+  capabilities.textDocument.completion.completionItem.commitCharactersSupport = true
+  capabilities.textDocument.completion.completionItem.tagSupport = { valueSet = { 1 } }
```
Comment (kylo252) [inline lua/lsp/init.lua:56]: None of this look common to me :( 
I think it's better to add it specifically to `sumneko` just so we don't get some crazy behavior.

Comment (abzcoding) [reply lua/lsp/init.lua:56]: they should not cause any damage, but you are right

**Comment by abzcoding** [comment]
those capabilities was unnecessary, since nvim-cmp adds them itself

**Review by kylo252 — APPROVED** [review]
