### PR TITLE
fix(peek): make sure popup_options are positive

### LINKED ISSUE #2369: Peek definition fails in C#
### Problem description

1. Open a C# file.
2. Move the cursor over a method call.
3. Press Space, l, p, d. (LSP Peek Definition).

An error message appears:

> Error executing vim.schedule lua callback: /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:42: 'width' key must be a positive Integer
stack traceback:
        [C]: in function 'nvim_open_win'
        /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:42: in function 'create_floating_file'
        /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:71: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:964: in function 'cb'
        vim.lua:285: in function <vim.lua:285>

### LunarVim version

5ee460f  chore(release): update changelog

### Neovim version (>= 0.6.1)

NVIM v0.6.1 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

Arch Linux

### Relevant log output

```shell
:checkhealth
Nothing suspicious.
```

### Screenshots

LSP info:
image

### PR DESCRIPTION
**Pull request by abzcoding**
# Description

@otto-gebb can you verify if this fixes your issue or not?

Fixes #2369

### CODE REVIEW

File: lua/lvim/lsp/peek.lua [hunk 1]
```diff
@@ -33,7 +33,7 @@ local function create_floating_file(location, opts)
     false
   )
   local width, height = vim.lsp.util._make_floating_popup_size(contents, opts)
-  opts = vim.lsp.util.make_floating_popup_options(width, height, opts)
+  opts = vim.lsp.util.make_floating_popup_options(math.max(width, 30), math.max(height, 10), opts)
```
Comment (kylo252) [inline lua/lvim/lsp/peek.lua:36]: maybe it's safer to use `vim.F.if_nil` instead? otherwise you need to validate you're not passing `nil`

```suggestion
  local if_nil = vim.F.if_nil
  opts = vim.lsp.util.make_floating_popup_options(if_nil(width, 30), if_nil(height, 10), opts)
```

**Review by kylo252 — APPROVED** [review]
LGTM! 🚀 

this entire function might have to be removed/refactored If #2369 is still broken, since it's relying on internal functions that aren't guaranteed to not change.

**Comment by otto-gebb** [comment]
@abzcoding I edited the file
`~/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua`, manually making the changes of this PR.

When I'm trying to "peek definition" of a symbol from a library I get the same error, except the line number in the call steck is now 44 (which means the code lines I added took effect).
> Error executing vim.schedule lua callback: /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:44: 'width' key must be a positive Integer
stack traceback:
        [C]: in function 'nvim_open_win'
        /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:44: in function 'create_floating_file'
        /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:73: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:964: in function 'cb'
        vim.lua:285: in function <vim.lua:285>

So I would say no, the changes don't fix the bug.

**Comment by abzcoding** [comment]
@kylo252 i think instead of if_nil we should've use the math.max 

@otto-gebb can you test this instead?
```lua
opts = vim.lsp.util.make_floating_popup_options(math.max(width, 30), math.max(height,10) , opts)
```

**Comment by otto-gebb** [comment]
@abzcoding with the latest proposed change (math.max) I get a different error:

> Error executing vim.schedule lua callback: /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:46: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:46: in function 'create_floating_file'
        /home/gebb/.local/share/lunarvim/lvim/lua/lvim/lsp/peek.lua:72: in function 'handler'
        /usr/share/nvim/runtime/lua/vim/lsp.lua:964: in function 'cb'
        vim.lua:285: in function <vim.lua:285>

**Comment by abzcoding** [comment]
> nvim_win_set_cursor

can you add this after the opts line you added up there?
and get a screenshot or sth

```lua
print(vim.inspect(range))
```

**Comment by otto-gebb** [comment]
@abzcoding sure. Had to execute `:messages` to show the `print`-ed value.
image

**Comment by abzcoding** [comment]
@otto-gebb sorry to bother you again, but could you add this one as well and get a screenshot
```lua
print(vim.inspect(contents)) -- this is the new one
print(vim.inspect(range))
opts = vim.lsp.util.make_floating_popup_options(math.max(width, 30), math.max(height, 10), opts)
```

**Comment by abzcoding** [comment]
yeah it seems like `nvim_buf_get_line` couldn't access the proper buffer content
while at it, can you do a 
```lua
print(vim.inspect(location))
print(bufnr)
```
on top of them

**Comment by abzcoding** [comment]
Yeah, I agree. We should print an error if LSP cannot find the proper content. Thank you for helping through the debugging process
