### PR TITLE
fix: correct runtimepath order

### LINKED ISSUE #3723: vimtex does not work
### Problem description

When `lervag/vimtex` is added as a plugin, it is not loaded, i.e., the command like ":VimtexClean" defined in `vimtex` can not be used. However, when use the 'rolling' branch of lunarvim, `vimtex` can be used correctly.

### LunarVim version

master-f4ec3fc

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-661+ga37c686d2

### Operating system/version

Ubuntu 22.04

### Steps to reproduce

The configure file is 
```lua
lvim.plugins = {
  { "lervag/vimtex",
    config = function()
      vim.g.vimtex_view_general_viewer = 'okular'
      vim.g.vimtex_view_general_options = [[--unique file:@pdf\#src:@line@tex]]
      vim.g.vimtex_quickfix_enabled = 1
      vim.g.vimtex_syntax_enabled = 1
      vim.g.vimtex_quickfix_mode = 0
    end,
    ft = 'tex'
  },
}
```
The command such as `:VimtexClean` can not be used after `Sync` the plugins. Only the command `:VimtexInverseSearch` can be used. 

I notice that the command `:VimtexInverseSearch` is defined in the `plugin` folder in the root directory of `vimtex` and more command such as `:VimtexClean` defined in the `autoload` folder in the root directory of `vimtex` can not be used.  However, all the commands works well when I use the `rolling` branch of `lunarvim`.

### Screenshots

`Vimtex` is said to be loaded when i open a `tex` file.

image

However, only the command `VimtexInverseSearch` is loaded.

image

### PR DESCRIPTION
**Pull request by LostNeophyte**
# Description

before: 
```sh
~/.config/lvim
/usr/share/nvim/site
~/.local/share/lunarvim/lvim
plugins # should be before `/usr/share/nvim/site`
plugins/after
~/.local/share/lunarvim/site/after
~/.config/lvimd/after
```

after:

```sh 
# now the priority is correct: 1.user 2.lvim 3.plugins 4.nvim
~/.config/lvim
~/.local/share/lunarvim/lvim
plugins
/usr/share/nvim/...
plugins/after
~/.local/share/lunarvim/site/after
~/.config/lvim/after
```

fixes #3723  #3941

## How Has This Been Tested?

`:set rtp?`

### CODE REVIEW

File: lua/lvim/plugin-loader.lua [hunk 1]
```diff
@@ -42,8 +42,19 @@ function plugin_loader.init(opts)
     vim.api.nvim_create_autocmd("User", { pattern = "LazyDone", callback = require("lvim.lsp").setup })
   end
 
-  vim.opt.runtimepath:append(lazy_install_dir)
```
Comment (kylo252) [inline lua/lvim/plugin-loader.lua:45]: have you tried just doing as the docs suggest in lazy?

```lua
  vim.opt.runtimepath:prepend(lazy_install_dir)
```

it seems to work fine for me, here's the full diff

```diff
diff --git a/init.lua b/init.lua
index 3fdf2a4e..5931817a 100644
--- a/init.lua
+++ b/init.lua
@@ -1,9 +1,11 @@
-local base_dir = vim.env.LUNARVIM_BASE_DIR
+vim.env.LUNARVIM_BASE_DIR = vim.env.LUNARVIM_BASE_DIR
   or (function()
     local init_path = debug.getinfo(1, "S").source
     return init_path:sub(2):match("(.*[/\\])"):sub(1, -2)
   end)()
 
+local base_dir = vim.env.LUNARVIM_BASE_DIR
+
 if not vim.tbl_contains(vim.opt.rtp:get(), base_dir) then
   vim.opt.rtp:append(base_dir)
 end
diff --git a/lua/lvim/plugin-loader.lua b/lua/lvim/plugin-loader.lua
index ddb6c179..f24f279f 100644
--- a/lua/lvim/plugin-loader.lua
+++ b/lua/lvim/plugin-loader.lua
@@ -42,8 +42,8 @@ function plugin_loader.init(opts)
     vim.api.nvim_create_autocmd("User", { pattern = "LazyDone", callback = require("lvim.lsp").setup })
   end
 
-  vim.opt.runtimepath:append(lazy_install_dir)
-  vim.opt.runtimepath:append(join_paths(plugins_dir, "*"))
+  vim.opt.runtimepath:prepend(lazy_install_dir)
 
   pcall(function()
     -- set a custom path for lazy's cache
```

File: init.lua [hunk 2]
```diff
@@ -5,7 +5,7 @@ local base_dir = vim.env.LUNARVIM_BASE_DIR
   end)()
 
 if not vim.tbl_contains(vim.opt.rtp:get(), base_dir) then
-  vim.opt.rtp:append(base_dir)
+  vim.opt.rtp:prepend(base_dir)
```
Comment (kylo252) [inline init.lua:8]: good catch!

**Review by ChristianChiarulli — APPROVED** [review]
