### PR TITLE
fix(lsp): correct map and prevent highlight leak of diagnostic signs in 0.6

### LINKED ISSUE #1880: [Bug]: Error executing vim.schedule lua callback: Vim:E849: Too many highlight and syntax groups
### Problem description

Open c++ project.
Code as normal, after 10min, this error show on every keystoke

I have to close neovim, and start again. But It happen again and agian every 10 min

### LunarVim version

lastest rolling 377cab434c79aa537820ba21bbcc44261304ed09

### Neovim version (>= 0.5)

NVIM v0.6.0-dev+493-g035d82e0d

### Relevant log output

```shell
:message
Error executing vim.schedule lua callback: Vim:E849: Too many highlight and syntax groups
Error executing vim.schedule lua callback: Vim:E849: Too many highlight and syntax groups
```

### Screenshots

Untitled

### I have

- [X] Read the readme
- [X] Read the wiki
- [X] Searched for similar issues

### PR DESCRIPTION
**Pull request by chase**
# Description

For Neovim nightly builds (versions greater than 0.5.1), every time the LSP server published diagnostics (quite frequently in my case), it would define and re-define a sign, leaving hundreds of cleared highlight groups.

Additionally, because position was being used instead of mapping by name, the highlight groups were incorrect.

This PR fixes both of these problems.

Fixes #1880

## How Has This Been Tested?

Use neovim nightly, open a decently sized document that has a supported and setup LSP.
Make an error that triggers a lot of diagnostic errors (for example an `{` in the middle of a function), then trigger cmp autocomplete and scroll through. This error should no longer occur while using this PR.

### CODE REVIEW

**Comment by chase** [comment]
All failed checks are from previous commits, FYI

**Comment by chase** [comment]
@maxxnino can you reproduce the error you were having before (#1880) while using the branch for this PR?

**Comment by maxxnino** [comment]
@chase i can confirm. it solved the problem

File: lua/lvim/lsp/init.lua [hunk 1]
```diff
@@ -136,6 +136,13 @@ function M.get_common_opts()
   }
 end
 
+local NVIM_05_TO_06_SIGN_NAMES = {
```
Comment (kylo252) [inline lua/lvim/lsp/init.lua:139]:
```suggestion
local LSP_SIGN_MAP = {
```

File: lua/lvim/lsp/init.lua [hunk 2]
```diff
@@ -144,7 +151,13 @@ function M.setup()
...
 
+  local isNvim06 = vim.fn.has "nvim-0.5.1" > 0
+
   for _, sign in ipairs(lvim.lsp.diagnostics.signs.values) do
+    local nvim06SignName = NVIM_05_TO_06_SIGN_NAMES[sign.name]
+    if isNvim06 and nvim06SignName then
+      vim.fn.sign_define(nvim06SignName, { texthl = nvim06SignName, text = sign.text, numhl = nvim06SignName })
+    end
     vim.fn.sign_define(sign.name, { texthl = sign.name, text = sign.text, numhl = sign.name })
   end
```
Comment (kylo252) [inline lua/lvim/lsp/init.lua:162]:
```suggestion
  local is_neovim_nightly = vim.fn.has "nvim-0.5.1" > 0

  for _, sign in ipairs(lvim.lsp.diagnostics.signs.values) do
    local  lsp_sign_name = LSP_SIGN_MAP[sign.name]
    if is_neovim_nightly and lsp_sign_name then
      vim.fn.sign_define(lsp_sign_name, { texthl = lsp_sign_name, text = sign.text, numhl = lsp_sign_name })
    else
      vim.fn.sign_define(sign.name, { texthl = sign.name, text = sign.text, numhl = sign.name })
    end
  end
```

**Review by kylo252 — CHANGES_REQUESTED** [review]

File: lua/lvim/lsp/init.lua (hunk 2 above)
Comment (kylo252) [reply lua/lvim/lsp/init.lua]: Don't we need the `else` here?

Comment (chase) [reply lua/lvim/lsp/init.lua]: No, the deprecated names for signs still need to be defined for plugins that haven't been updated yet.

**Review by kylo252 — APPROVED** [review]
