### PR TITLE
fix(autocmd): actually use the format wrapper

### LINKED ISSUE #2559: Latest version of lunarvim depends on neovim version 0.8
### Problem description

The following error is output when saving

````
Error executing lua callback: ...be/.local/share/lunarvim/lvim/lua/lvim/core/autocmds.lua:80: attempt to call field 'format' (a nil value)
````

The function ``vim.lsp.buf.format`` that is causing the error is a function added in neovim 0.8. Therefore, "formatting" should be used instead of "format" to ensure that it works with neovim version 0.7.

### LunarVim version

9ad3510

### Neovim version (>= 0.7)

NVIM v0.7.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser

### Operating system/version

NAME="Garuda Linux" PRETTY_NAME="Garuda Linux" ID=garuda ID_LIKE=arch BUILD_ID=rolling ANSI_COLOR="38;2;23;147;209" HOME_URL="https://garudalinux.org/" DOCUMENTATION_URL="https://wiki.garudalinux.org/" SUPPORT_URL="https://forum.garudalinux.org/" BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/" LOGO=garudalinux

### Relevant log output

```shell
null-ls: require("null-ls.health").check()
========================================================================
  - ERROR: black: the command "black" is not executable.
  - ERROR: isort: the command "isort" is not executable.
  - ERROR: prettier: the command "prettier" is not executable.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - WARNING: **Ruby**: not available
  - WARNING: **RubyGem**: not available
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - ERROR: **npm**: not available
  - WARNING: **julia**: not available
  - OK: **gzip**: `gzip 1.12`
  - OK: **curl**: `curl 7.83.0 (x86_64-pc-linux-gnu) libcurl/7.83.0 OpenSSL/1.1.1n zlib/1.2.12 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.2 libpsl/0.21.1 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.47.0`
  - OK: **wget**: `GNU Wget 1.21.3 built on linux-gnu.`
  - OK: **python3**: `Python 3.10.4`
  - OK: **Go**: `go version go1.18.1 linux/amd64`
  - OK: **bash**: `GNU bash, バージョン 5.1.16(1)-release (x86_64-pc-linux-gnu)`
  - OK: **sh**: `Ok`
  - OK: **tar**: `tar (GNU tar) 1.34`
  - WARNING: **pip3**: not available
  - OK: **node**: `v17.9.0`
  - OK: **cargo**: `cargo 1.59.0 (49d8809dc 2022-02-10)`
  - OK: **java**: `Ok`
  - OK: **javac**: `javac 11.0.15`

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v17.9.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (GCC) 11.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - scala          ✓ . ✓ . ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - java           x ✓ . ✓ ✓ 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

## The following errors have been detected:
  - ERROR: java(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 2028
    java(highlights) is concatenated from the following files:
    | [ERROR]:"/home/watanabe/.local/share/lunarvim/site/pack/packer/start/nvim-treesitter/queries/java/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:172: query: invalid node type at position 2028

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: wl-copy

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.10.4
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v17.9.0
  - INFO: Nvim node.js host: /home/watanabe/.config/yarn/global//node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 13.0.0
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

## Telescope Extension: `projects`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /home/watanabe/.cache/nvim/lsp.log
  - INFO: Log size: 192 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for scala: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gb"**
  - INFO: rhs: `<Plug>(comment_toggle_blockwise)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Plug>(comment_toggle_linewise)`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 1, lhs: **"gD"**
  - INFO: old rhs: `<cmd>lua vim.lsp.buf.definition()<CR>`
  - INFO: new rhs: `<cmd>lua require("which-key").execute(9)<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 1, lhs: **"K"**
  - INFO: old rhs: `<cmd>lua vim.lsp.buf.hover()<CR>`
  - INFO: new rhs: `<cmd>lua require("which-key").execute(12)<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 1, lhs: **"gr"**
  - INFO: old rhs: `<cmd>lua vim.lsp.buf.references()<CR>`
  - INFO: new rhs: `<cmd>lua require("which-key").execute(13)<cr>`

BufWritePre Autocommands for "*" の処理中にエラーが検出されました:
Error executing lua callback: ...be/.local/share/lunarvim/lvim/lua/lvim/core/autocmds.lua:80: attempt to call
 field 'format' (a nil value)
stack traceback:
        ...be/.local/share/lunarvim/lvim/lua/lvim/core/autocmds.lua:80: in function <...be/.local/share/lunar
vim/lvim/lua/lvim/core/autocmds.lua:79>
"lua/lvim/core/autocmds.lua" 156L, 4732B 書込み
170 行がヤンクされました
続けるにはENTERを押すかコマンドを入力してください
```

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by baku1101**
Fixes #2559

### CODE REVIEW

File: lua/lvim/core/autocmds.lua [hunk 1]
```diff
@@ -77,7 +77,7 @@ function M.enable_format_on_save()
     group = "lsp_format_on_save",
     pattern = opts.pattern,
     callback = function()
-      vim.lsp.buf.format { timeout_ms = opts.timeout, filter = opts.filter }
+      vim.lsp.buf.formatting { timeout_ms = opts.timeout, filter = opts.filter }
```
Comment (kylo252) [inline lua/lvim/core/autocmds.lua:80]:
```suggestion
      require("lvim.lsp.utils").format { timeout_ms = opts.timeout, filter = opts.filter }
```

**Review by kylo252 — CHANGES_REQUESTED** [review]
must've missed that, sorry about that!

**Review by kylo252 — APPROVED** [review]
