### PR TITLE
fix: don't install desktop file w/o xdg-desktop-menu

### LINKED ISSUE #3216: [WSL] Installation doesn't go through
### Problem description

First installation of nightly version of Lunarvim in WSL encountering an error in creation of desktop file causing the LunarVim installation not proceeding to install everything including the necessary plugins.

### LunarVim version

rolling-ea1ebda

### Neovim version (>= 0.8.0)

NVIM v0.9.0-dev-77-gf175ca9f7

### Operating system/version

WSL

### Steps to reproduce

_No response_

### support info

Nan

### Screenshots

image

After creating `.local/share/applications` folder
image

### PR DESCRIPTION
**Pull request by opalmay**
Fixes #3216

### CODE REVIEW

File: utils/installer/install.sh [hunk 1]
```diff
@@ -458,7 +458,7 @@ function setup_lvim() {
 function create_desktop_file() {
   OS="$(uname -s)"
   # TODO: Any other OSes that use desktop files?
-  [ "$OS" != "Linux" ] && return
+  ([ "$OS" != "Linux" ] || ! command -v xdg-desktop-menu &>/dev/null) && return
   echo "Creating desktop file"
 
   for d in "$LUNARVIM_BASE_DIR"/utils/desktop/*/; do
```
Comment (kylo252) [inline utils/installer/install.sh:464]: please re-work this to use `xdg-desktop-menu` instead of manually copying the file(s)

I think this should work

```sh
xdg-desktop-menu install --novendor ./utils/desktop/lvim.desktop
```

too bad that `xdg-icon-resource` doesn't support svg🤦

**Review by kylo252 — CHANGES_REQUESTED** [review]

**Review by kylo252 — APPROVED** [review]
LGTM! 🚀
