### PR TITLE
fix: set runtime directories correctly

### LINKED ISSUE #1352: [BUG]: Runtime directories are not set correctly
# Description

There are inconsistencies in how `runtimepath` and `packpath` are. There neovim's defaults that weren't removed in some cases, and in other instances, lunarvim's directory are missing.

That's why the shim that's used to launch lunarvim contains a command for modifying `runtimepath`

https://github.com/LunarVim/LunarVim/blob/0bf6fd68c625396d83eb8fca8d7248c5543ae6f1/utils/bin/lvim#L3

Here's what lunarvim gives me for `&packpath` and `&rtp`
```lua
> rtp list:
"/home/hatsu/.local/share/lunarvim/lvim/after"
"/home/hatsu/.local/share/nvim/site"
"/home/hatsu/.local/share/nvim/site/after"
"/home/hatsu/.local/share/lunarvim/lvim"
"/home/hatsu/.config/lvim"

> pack list:
"/home/hatsu/.config/lvim"
"/home/hatsu/.local/share/lunarvim/site"
"/home/hatsu/.local/share/nvim/site/after"
```

Here's what the default one should be:
```lua
> rtp list:
"/home/hatsu/.config/nvim"
"/home/hatsu/.local/share/nvim/site"
"/home/hatsu/.local/share/nvim/site/after"
"/home/hatsu/.config/nvim/after"

> pack list:
"/home/hatsu/.config/nvim"
"/home/hatsu/.local/share/nvim/site"
"/home/hatsu/.local/share/nvim/site/after"
"/home/hatsu/.config/nvim/after"
```

### PR DESCRIPTION
**Pull request by kylo252**
# Description

This also simplifies the way to invoke LunarVim to just be:
`nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua"`

Fixes #1352

## How Has This Been Tested?

Add this to test the rtp variable more easily

```lua
print("-- rtp list: ")
local rtp_list = vim.opt.rtp:get()
local user_rtp_list = {}
for _, path in pairs(rtp_list) do
    if vim.startswith(path, "/home") and not path:match(".*packer.*") then
        table.insert(user_rtp_list, path)
        print(vim.inspect(path))
    end
end

print("-- pack list: ")
local pack_list = vim.opt.packpath:get()
local user_pack_list = {}
for _, path in pairs(pack_list) do
    if vim.startswith(path, "/home") and not path:match(".*packer.*") then
        table.insert(user_pack_list, path)
        print(vim.inspect(path))
    end
end
```

You can now start LunarVim by just using `nvim -u "$LUNARVIM_RUNTIME_DIR/lvim/init.lua"` :)

### CODE REVIEW

File: init.lua [hunk 1]
```diff
@@ -1,16 +1,24 @@
...
+--/_____/\__,_/_/ /_/\__,_/_/    |___/_/_/ /_/ /_/
 
-  set runtimepath-=~/.config/nvim
-  set runtimepath-=~/.config/nvim/after
-  set runtimepath+=~/.config/lvim
-  set runtimepath^=~/.local/share/lunarvim/lvim/after
-]]
--- vim.opt.rtp:append() instead of vim.cmd ?
+--- Bootstrap
+vim.opt.rtp:append(os.getenv "HOME" .. "/.local/share/lunarvim/lvim")
```
Comment (Tastyep) [inline init.lua:8]: local home = os.getenv "HOME"

File: init.lua [hunk 2]
```diff
@@ -1,16 +1,24 @@
-vim.cmd [[
-  set packpath-=~/.config/nvim
-  set packpath-=~/.config/nvim/after
-  set packpath-=~/.local/share/nvim/site
-  set packpath^=~/.local/share/lunarvim/site
-  set packpath^=~/.config/lvim
+--    __                          _    ___
```
Comment (Tastyep) [inline init.lua:1]: Do we need this ?

**Review by Tastyep — CHANGES_REQUESTED** [review]

File: init.lua (hunk 1 above)
Comment (vlcinsky) [reply init.lua:8]: or
```
local home = vim.loop.os_homedir()
```
what shall simplify future modifications for MS Windows environment.

Anyway, it seems usable as is with the repeated `os.getenv`

File: init.lua (hunk 2 above)
Comment (vlcinsky) [reply init.lua:1]: I would remove this banner.

**Review by vlcinsky — APPROVED** [review]
The PR is very well usable as is.

I like the care of configuring all the paths not leaving so much space for unexpected side effects.

There are only minor things which are not affecting usability.

File: init.lua (hunk 2 above)
Comment (kylo252) [reply init.lua:1]: rip banner 😢

**Review by Tastyep — APPROVED** [review]

**Review by vlcinsky — APPROVED** [review]
